openapi: 3.0.3
info:
  title: BearingPoint Recruiting - Bank
  version: "1"
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: foo
    description: blubb
paths:
  /hellos:
    get:
      tags:
        - foo
      summary: blubb
      description: blubb
      operationId: getHellos
      security:
        - user_id: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloList'
        500:
          $ref: '#/components/responses/Problem'

components:
  schemas:
    HelloList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Hello'
      required:
        - items
    Hello:
      type: object
      properties:
        data:
          type: string
          description: sfsdfasdf
          example: hello world
      required:
        - data

  responses:
    Problem:
      description: Error
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              title:
                type: string
                description: >
                  A short, human-readable summary of the problem type.
                example: Service Unavailable
              status:
                type: integer
                format: int32
                description: >
                  The HTTP status code generated by the origin server for this occurrence of the problem.
                minimum: 100
                maximum: 600
                exclusiveMaximum: true
                example: 503
              detail:
                type: string
                description: >
                  A human readable explanation specific to this occurrence of the problem.
                example: Connection to database timed out
            required:
              - title
              - status

  securitySchemes:
    user_id:
      type: apiKey
      name: x-user-id
      in: header
