spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
  jpa:
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
  h2:
    console:
      enabled: true
